FROM openjdk:21-jdk-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y netcat maven && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/config && \
    mkdir -p /app/logs && \
    mkdir -p /app/temp

RUN git clone https://github.com/tommot20077/FileManagement.git source && \
    cd /app/source && \
    mvn clean package -DskipTests && \
    mv target/*.jar /app/app.jar && \
    rm -rf /app/source && \
    cd /app

COPY wait-init.sh /app/wait-init.sh
RUN chmod +x /app/wait-init.sh

HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1

# 如果你的 compose 有更改，請確保這裡的環境變數也有更改
CMD ["/app/wait-init.sh", "filemanager_mysql", "3306", "60", "/app/wait-init.sh", "filemanager_mongo", "27017", "60", "/app/wait-init.sh", "filemanager_redis", "6381", "60", "java", "-jar", "app.jar"]